"""Tests for data cleaning."""
import pytest
from data.cleaner import CodeCleaner


def test_cleaner_accepts_valid_code():
    """Test that cleaner accepts quality code."""
    config = {"min_file_size": 100, "max_file_size": 100000}
    cleaner = CodeCleaner(config)

    valid_code = """def fibonacci(n):
    \"\"\"Calculate fibonacci number.\"\"\"
    if n <= 1:
        return n
    return fibonacci(n-1) + fibonacci(n-2)

def main():
    for i in range(10):
        print(f"fib({i}) = {fibonacci(i)}")

if __name__ == "__main__":
    main()
"""
    assert cleaner.is_valid_code(valid_code)


def test_cleaner_rejects_short_code():
    """Test that cleaner rejects code that's too short."""
    config = {"min_file_size": 100, "max_file_size": 100000}
    cleaner = CodeCleaner(config)

    short_code = "x = 1"
    assert not cleaner.is_valid_code(short_code)


def test_cleaner_rejects_autogenerated():
    """Test that cleaner rejects auto-generated code."""
    config = {"min_file_size": 100, "max_file_size": 100000}
    cleaner = CodeCleaner(config)

    autogen_code = "# TODO: auto-generated\n" + "x = 1\n" * 50
    assert not cleaner.is_valid_code(autogen_code)


def test_cleaner_rejects_single_line():
    """Test that cleaner rejects single-line code."""
    config = {"min_file_size": 100, "max_file_size": 100000}
    cleaner = CodeCleaner(config)

    single_line = "x = 1; y = 2; z = 3; a = 4; b = 5; c = 6; d = 7; e = 8; f = 9; g = 10; h = 11; i = 12; j = 13; k = 14; l = 15"
    assert not cleaner.is_valid_code(single_line)
