"""Data cleaning and filtering utilities."""


class CodeCleaner:
    """Filter and clean code data."""

    def __init__(self, config):
        self.config = config
        self.min_size = config.get("min_file_size", 100)
        self.max_size = config.get("max_file_size", 100000)

    def is_valid_code(self, code):
        """Check if code sample is valid and high-quality.

        Args:
            code: Code string to validate

        Returns:
            True if code passes quality checks
        """
        if not isinstance(code, str):
            return False

        code_len = len(code)

        # Check length
        if code_len < self.min_size or code_len > self.max_size:
            return False

        # Filter auto-generated code
        if "TODO: auto-generated" in code or "autogenerated" in code.lower():
            return False

        # Filter minified code
        if code.count("\n") < 2:
            return False

        # Filter mostly comments
        lines = code.split("\n")
        comment_lines = sum(1 for line in lines if line.strip().startswith("#"))
        if comment_lines / len(lines) > 0.8:
            return False

        return True

    def clean(self, dataset):
        """Apply quality filters to dataset.

        Args:
            dataset: Hugging Face Dataset

        Returns:
            Filtered dataset
        """
        return dataset.filter(
            lambda x: self.is_valid_code(x.get("content", ""))
        )
